name: qrserv
description: Transfer files with ease over a network.

publish_to: 'none'

version: 0.9.13+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # To be merged https://github.com/akshathjain/sliding_up_panel/pull/230
  ##sliding_up_panel: ^1.0.2
  sliding_up_panel:
    git:
      url: https://github.com/uintdev/sliding_up_panel.git
  
  # To be merged...
  ##file_picker_cross: ^4.2.7
  file_picker_cross:
    git:
      url: https://github.com/uintdev/file_picker_cross.git
      #url: https://gitlab.com/testapp-system/file_picker_cross.git
  
  path_provider: ^2.0.1
  filesize_ns: ^1.1.0

  # [qr_flutter] has a pull request regarding ns but not merged
  # https://github.com/theyakka/qr.flutter/pull/129
  ##qr_flutter: ^3.1.0
  qr_flutter:
    git:
      url: https://github.com/fzyzcjy/qr.flutter.git
      ref: 2f8c8b7b0aa3869f03a24f181724069c3f5ee6cd
  
  watcher: ^1.0.0
  package_info_plus: ^1.0.0
  url_launcher: ^6.0.2
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  auto_size_text: ^3.0.0-nullsafety.0
  oktoast: ^3.0.0

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 405e6c5476fbdfd3859cf2f8570b21afb692ea3a

  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Regular.ttf
